### ISSUE TITLE
Checkpoints link is invalid

### ISSUE THREAD

**Issue by 3019234115** [microsoft/ReCo#6]
I can't downloas the Checkpoints through link : https://unitab.blob.core.windows.net/data/reco/reco_coco.ckpt .
    I tried : wget https://unitab.blob.core.windows.net/data/reco/reco_coco.ckpt
    but get message:  --2023-06-19 21:36:47--  https://unitab.blob.core.windows.net/data/reco/reco_coco.ckpt
    正在解析主机 unitab.blob.core.windows.net (unitab.blob.core.windows.net)... 20.60.62.36
    正在连接 unitab.blob.core.windows.net (unitab.blob.core.windows.net)|20.60.62.36|:443... 已连接。
    已发出 HTTP 请求，正在等待回应... 404 The specified blob does not exist.
    2023-06-19 21:36:51 错误 404：The specified blob does not exist.。

I also tried : ./azcopy copy https://unitab.blob.core.windows.net/data/reco/reco_laion.ckpt ./ckpt --recursive
but got message : INFO: Scanning...
INFO: Autologin not specified.
failed to perform copy command due to error: failed to initialize enumerator: The specified file was not found.

so can you give other way to download the checkpoint? Or what should I do ? ( Am I doing something wrong?)

**Comment by 3019234115** [comment]
I use MAC temeral

**Comment by AlmogDeepKeep** [comment]
I'm getting the same error, the links are not working

**Comment by zyang-ur** [comment]
Updated with correct links, thanks!

**Comment by rB080** [comment]
Somehow this doesn't work on wget but I can download when I click the links on Chrome. Anybody else facing this issue? Is there a workaround for this??
Do I specifically have to use AZCopy for the datasets or can I wget it, because I face the same issue while wget-ing the dataset link as well...

**Comment by AlmogDeepKeep** [comment]
The links for the model weights work for me , but not the dataset link

**Comment by zyang-ur** [comment]
Since the dataset link is a folder, it would require using Azcopy. Wget will only work for single files according to my understanding.

**Comment by rB080** [comment]
I see...thanks!
