### ISSUE TITLE
Questions Regarding 'pad_caption' and 'crop_caption' in Dataset

### ISSUE THREAD

**Issue by uehara-mech** [microsoft/ReCo#7]
I've recently downloaded your dataset from the link provided in your Readme file. In particular, I've been looking into `coco_allbox_gitcaption_coco.json` and `lvis_allbox_gitcaption_train.json` files.

I noticed that each box's data includes two types of captions: `pad_caption` and `crop_caption`.
Could you please provide some clarity on what these two terms represent? I'm interested to understand how each is generated and what differentiates the two.

**Comment by uehara-mech** [comment]
ALso, what is the difference between `coco_allbox_gitcaption_coco.json` and `coco_allbox_gitcaption.json`, `lvis_allbox_gitcaption_train.json` and `lvis_allbox_gitcaption.json`?

**Comment by zyang-ur** [comment]
That's all related to regional caption generation, i.e., different image pre-processing and ckpt variants from the used GIT model. Please see the data loader for the exact setup (i.e., coco_allbox_gitcaption.json).

**Comment by uehara-mech** [comment]
Thank you for the clarification!

**Comment by rfuruta** [comment]
Related to the above questions, what are 'iou' in those json files? How did you calculate them?

**Comment by zyang-ur** [comment]
"iou" is the size of each region
